2021-12-03 11:03:37,232 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-03 11:15:33,131 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-03 11:16:41,751 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-03 11:16:45,116 ERROR: Exception on /edit_profile [GET] [in /home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/app/routes.py", line 82, in edit_profile
    form = EditProfileForm()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-12-03 11:16:49,697 ERROR: Exception on /edit_profile [GET] [in /home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/app/routes.py", line 82, in edit_profile
    form = EditProfileForm()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-12-03 11:17:03,737 ERROR: Exception on /edit_profile [GET] [in /home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/app/routes.py", line 82, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-12-03 11:17:45,160 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-03 11:19:59,660 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 20:24:24,519 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 20:24:43,466 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 21:12:37,041 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 21:13:30,931 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 21:15:41,708 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-06 21:49:39,437 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-07 09:26:05,710 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-07 14:37:22,398 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-07 14:56:36,485 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-07 15:10:51,193 INFO: Microblog statup [in /home/pontotel/Documents/Honorato/Flask/microblog/app/__init__.py:44]
2021-12-07 15:10:52,781 ERROR: Exception on /index [GET] [in /home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/pontotel/Documents/Honorato/Flask/microblog/app/templates/index.html", line 24, in template
    {% enfif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'enfif'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
